name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write

env:
  USER: ${{ github.repository_owner }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  SERVER: ghcr.io
  IMAGE_NAME: pipeline
  IMAGE_TAG: dev

jobs:
  push-ghcr:
    name: Build and push image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Build the image
      run: docker build . --tag ${{ env.SERVER }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Login to registry
      run: >
        echo ${{ secrets.GITHUB_TOKEN }} |
        docker login -u ${{ env.USER }} --password-stdin ${{ env.SERVER }}

    - name: Push to registry
      run: docker push ${{ env.SERVER }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
