name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY_USER: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_SERVER: ghcr.io
  IMAGE_NAME: pipeline
  IMAGE_TAG: dev

jobs:
  push-ghcr:
    name: Build and push image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Build the image
      run: docker build . --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Login to registry
      run: >
        echo ${{ secrets.GITHUB_TOKEN }} |
        docker login -u ${{ env.REGISTRY_USER }} --password-stdin ${{ env.REGISTRY_SERVER }}

    - name: Push to registry
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
